name: gathertown
version: 0.2.8
summary: A better way to meet.
description: |
  Electron wrapper for Gather Town
base: core22
confinement: strict
grade: stable
compression: lzo
architectures:
- build-on: amd64

apps:
  gathertown:
    command: out/gathertown-linux-x64/gathertown --no-sandbox
    extensions: [gnome]
    plugs:
    - browser-support
    - network
    - network-bind
    - audio-playback
    - audio-record
    - camera
    - home
    - desktop
    - opengl
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  gathertown:
    plugin: nil
    source: .
    override-build: |
        npm install
        npm run build:package
        #cp -rv ./out/gathertown-linux-* $SNAPCRAFT_PART_INSTALL/gathertown
        #chmod -R +rx $SNAPCRAFT_PART_INSTALL/gathertown
        chmod -R +xr ./out
        cp -rv ./out $SNAPCRAFT_PRIME/
        ls -lh $SNAPCRAFT_PRIME
        #chmod -R +x $SNAPCRAFT_PRIME/gathertown
        #ls -lh $SNAPCRAFT_PRIME
    build-snaps:
    - node/18/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
